package com.amalfi.entity;
// Generated 5 apr 2024, 21:23:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Eventi generated by hbm2java
 */

@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
public class Eventi {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer idevento;
	private Long userid;
	private Date dataevento;
	private String titolo;
	private String descrizione;
	private String note;
	private String url;

	
}
