package com.amalfi.entity;
// Generated 5 apr 2024, 21:23:38 by Hibernate Tools 4.3.6.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Utenti generated by hbm2java
 */

@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
public class Utenti  {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer idutente;
	private String email;
	private String password;
	private String nome;
	private String cognome;
	private Boolean abilitato;
	private Boolean eliminato;

	
}
